/** @type {import('tailwindcss').Config} */
const config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "#ffffff",
        foreground: "#10231f",
        primary: {
          DEFAULT: "#004b3f",
          soft: "#e9fff1",
          tint: "#c5f8d8",
          contrast: "#ffffff",
        },
        secondary: "var(--color-muted)",
        accent: {
          DEFAULT: "#f06a5d",
          foreground: "var(--color-background)",
          soft: "#f7bd66",
          strong: "#8a003f",
          surface: "#fde5ea",
          success: "#13a563",
          danger: "#b3263a",
          provider: {
            one: "#4285F4",
            two: "#34A853",
            three: "#FBBC05",
            four: "#EA4335",
          },
          warning: {
            DEFAULT: "#7a4a00",
            surface: "#fff4de",
          },
        },
        surface: {
          DEFAULT: "#ffffff",
          2: "var(--color-surface-soft)",
          soft: "#f7f7f5",
          subtle: "#f2f0ee",
          media: "#c8a37a",
          info: "#bfeeff",
          warm: "#f4eee7",
          muted: "#f6f2ee",
        },
        muted: {
          DEFAULT: "#5f5f5a",
          subtle: "#8a8a84",
          line: "#e7e3df",
          "line-strong": "#d7d0ca",
        },
        hairline: "var(--color-muted-line)",
        info: {
          DEFAULT: "var(--color-surface-info)",
          text: "var(--color-primary)",
        },
        success: {
          DEFAULT: "var(--color-accent-success)",
          surface: "color-mix(in srgb, var(--color-accent-success) 12%, var(--color-surface))",
        },
        warning: {
          DEFAULT: "var(--color-accent-warning)",
          surface: "var(--color-accent-warning-surface)",
        },
        danger: {
          DEFAULT: "var(--color-accent-danger)",
          surface: "var(--color-accent-surface)",
        },
      },
      fontFamily: {
        sans: ["var(--font-dm-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ["var(--font-fraunces)", "ui-serif", "Georgia", "serif"],
      },
      fontSize: {
        eyebrow: "0.625rem",
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        brand: "1.125rem",
        "5xl": "3rem",
        "6xl": "3.75rem",
        "7xl": "4.5rem",
        "8xl": "6rem",
      },
      fontWeight: {
        normal: "400",
        semibold: "600",
        bold: "700",
      },
      spacing: {
        0: "0",
        0.5: "0.125rem",
        1: "0.25rem",
        1.5: "0.375rem",
        2: "0.5rem",
        2.5: "0.625rem",
        3: "0.75rem",
        3.5: "0.875rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        7: "1.75rem",
        8: "2rem",
        9: "2.25rem",
        10: "2.5rem",
        11: "2.75rem",
        12: "3rem",
        14: "3.5rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
        28: "7rem",
        32: "8rem",
        64: "16rem",
        72: "18rem",
      },
      borderRadius: {
        none: "0",
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "panel-lg": "1rem",
        "panel-xl": "1.25rem",
        "panel-2xl": "1.5rem",
        "shell-lg": "1.35rem",
        shell: "2rem",
        "shell-inner": "calc(2rem - 0.5rem)",
      },
      lineHeight: {
        hero: "0.98",
      },
      letterSpacing: {
        section: "0.14em",
        badge: "0.16em",
        label: "0.2em",
      },
      transitionTimingFunction: {
        soft: "cubic-bezier(0.32, 0.72, 0, 1)",
      },
      scale: {
        press: "0.98",
      },
      minHeight: {
        viewport: "100dvh",
        auth: "calc(100dvh - 88px)",
        "interview-shell": "560px",
        "interview-panel": "540px",
      },
      maxHeight: {
        hero: "520px",
      },
      height: {
        hero: "430px",
      },
      gridTemplateColumns: {
        progress: "1fr 80px",
        practice: "0.8fr 1.2fr",
        story: "0.34fr 0.66fr",
        questions: "0.42fr 0.58fr",
        "report-score": "1fr 280px",
        "report-body": "1.15fr 0.85fr",
        interview: "280px 1fr 280px",
      },
      boxShadow: {
        mockup: "0 18px 45px color-mix(in srgb, var(--color-primary) 24%, transparent)",
        floating: "0 14px 34px color-mix(in srgb, black 16%, transparent)",
        lifted: "0 18px 45px color-mix(in srgb, black 18%, transparent)",
        panel: "0 18px 45px color-mix(in srgb, var(--color-primary) 14%, transparent)",
        glass: "0 24px 80px color-mix(in srgb, rgb(49 65 58) 12%, transparent), inset 0 1px 0 color-mix(in srgb, var(--color-surface) 90%, transparent)",
        shell: "0 30px 90px color-mix(in srgb, rgb(49 65 58) 12%, transparent)",
        "shell-strong": "0 30px 90px color-mix(in srgb, rgb(49 65 58) 14%, transparent)",
        inset: "inset 0 1px 0 color-mix(in srgb, var(--color-surface) 92%, transparent)",
        input: "inset 0 1px 0 color-mix(in srgb, var(--color-surface) 90%, transparent)",
        avatar: "0 18px 44px color-mix(in srgb, var(--color-primary) 18%, transparent)",
      },
    },
  },
};

module.exports = config;
